FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY ./packages ./packages
COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./apps/web ./apps/web
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

RUN pnpm install --frozen-lockfile=false


RUN cd packages/common && pnpm run build
RUN cd packages/db && pnpm run build
RUN cd apps/web && pnpm run build

WORKDIR /app/apps/web

EXPOSE 3000

CMD ["pnpm", "run", "start"]